set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default:
    @just --list

run:
    mvn compile exec:java -Dexec.mainClass="org.example.lecw4.App"

debug:
    mvnDebug compile exec:java -Dexec.mainClass="org.example.lecw4.App"

test:
    mvn test
